---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/main_effects_slp/main_effects_slp.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/96672/articles/192848/master/folder/figures/main_effects_slp"
    url: "/users/96672/articles/192848/master/file/figures/main_effects_slp/main_effects_slp.png"
