---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/slope_composite/slope_composite.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/96672/articles/192848/master/file/figures/slope_composite/slope_composite.png"
    folder_url: "/users/96672/articles/192848/master/folder/figures/slope_composite"
