---
version: 2
multicolumn: false
web-width: '1000'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mean_betas_threshclust/mean_betas_threshclust.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/96672/articles/192848/master/file/figures/mean_betas_threshclust/mean_betas_threshclust.png"
    folder_url: "/users/96672/articles/192848/master/folder/figures/mean_betas_threshclust"
